<?php declare(strict_types=1);

namespace Base3\Database\Api;

/**
 * Interface IDatabase
 *
 * Defines a basic database access interface for executing queries and handling connections.
 */
interface IDatabase {

	/**
	 * Establishes a connection to the database.
	 *
	 * @return void
	 */
	public function connect();

	/**
	 * Checks whether a connection to the database is active.
	 *
	 * @return bool True if connected, false otherwise
	 */
	public function connected();

	/**
	 * Closes the database connection.
	 *
	 * @return void
	 */
	public function disconnect();

	/**
	 * Executes a query that modifies data (INSERT, UPDATE, DELETE).
	 *
	 * @param string $query SQL statement
	 * @return void
	 */
	public function nonQuery($query);

	/**
	 * Executes a query that returns a single scalar value.
	 *
	 * @param string $query SQL statement
	 * @return mixed Scalar result (e.g. int, string)
	 */
	public function scalarQuery($query);

	/**
	 * Executes a query that returns one row as an associative array.
	 *
	 * @param string $query SQL statement
	 * @return array|null Associative row or null if no result
	 */
	public function singleQuery($query);

	/**
	 * Executes a query that returns a list of scalar values (one column).
	 *
	 * @param string $query SQL statement
	 * @return array List of scalar values
	 */
	public function &listQuery($query);

	/**
	 * Executes a query that returns multiple rows as associative arrays.
	 *
	 * @param string $query SQL statement
	 * @return array List of rows
	 */
	public function &multiQuery($query);

	/**
	 * Returns the number of rows affected by the last query.
	 *
	 * @return int Number of affected rows
	 */
	public function affectedRows();

	/**
	 * Returns the ID generated by the last INSERT operation.
	 *
	 * @return int|string Insert ID (may be numeric or UUID depending on backend)
	 */
	public function insertId();

	/**
	 * Escapes a string for safe use in SQL queries.
	 *
	 * @param string $str Input string
	 * @return string Escaped string
	 */
	public function escape($str);

	/**
	 * Checks if the last query resulted in an error.
	 *
	 * @return bool True if an error occurred
	 */
	public function isError();

	/**
	 * Returns the numeric error code from the last error.
	 *
	 * @return int|null Error code or null if no error
	 */
	public function errorNumber();

	/**
	 * Returns the message associated with the last error.
	 *
	 * @return string|null Error message or null if no error
	 */
	public function errorMessage();

}

