<?php declare(strict_types=1);

namespace Base3\Database\Api;

/**
 * Interface IDatabase
 *
 * Abstraction for database access used throughout the framework.
 *
 * Design principles:
 * ------------------
 * - Implementations MUST support lazy connections.
 * - Calling connect() multiple times MUST be safe.
 *
 * Consumers of this interface:
 * - SHOULD call connect() proactively before executing queries to guarantee connectivity
 * - MAY call connect() redundantly without side effects
 *
 * This explicit contract avoids:
 * - implicit connection assumptions
 * - "am I connected?" conditionals in application code
 * - accidental early or duplicate connections
 */
interface IDatabase {

	/**
	 * Establishes a database connection if not already connected.
	 *
	 * Semantics:
	 * - Implementations MUST implement this as a lazy connect.
	 * - Calling this method when already connected MUST be a no-op.
	 * - Calling this method multiple times MUST be safe.
	 */
	public function connect(): void;

	/**
	 * Indicates whether a database connection is currently active.
	 *
	 * @return bool True if a connection is currently established.
	 */
	public function connected(): bool;

	/**
	 * Closes the database connection.
	 *
	 * Semantics:
	 * - After disconnect(), connected() MUST return false.
	 * - A subsequent call to connect() MUST re-establish the connection.
	 */
	public function disconnect(): void;

	/**
	 * Begins a database transaction.
	 *
	 * Semantics:
	 * - Implementations SHOULD throw if no connection exists (or auto-connect).
	 * - Nested transactions are implementation-defined (no requirement here).
	 */
	public function beginTransaction(): void;

	/**
	 * Commits the current transaction.
	 */
	public function commit(): void;

	/**
	 * Rolls back the current transaction.
	 */
	public function rollback(): void;

	/**
	 * Executes a query that modifies data (INSERT, UPDATE, DELETE).
	 */
	public function nonQuery(string $query): void;

	/**
	 * Executes a query that returns a single scalar value.
	 *
	 * Semantics:
	 * - If the query yields no rows, NULL SHOULD be returned.
	 * - If multiple rows are returned, the first value is used.
	 *
	 * @return mixed Scalar value or NULL.
	 */
	public function scalarQuery(string $query): mixed;

	/**
	 * Executes a query that returns a single row as an associative array.
	 *
	 * Semantics:
	 * - If no row is found, NULL MUST be returned.
	 * - If multiple rows are found, only the first row is returned.
	 *
	 * @return array|null Row or NULL.
	 */
	public function singleQuery(string $query): ?array;

	/**
	 * Executes a query that returns a list of scalar values (single column).
	 *
	 * @return array List of scalar values.
	 */
	public function &listQuery(string $query): array;

	/**
	 * Executes a query that returns multiple rows as associative arrays.
	 *
	 * @return array List of associative rows.
	 */
	public function &multiQuery(string $query): array;

	/**
	 * Returns the number of rows affected by the last data-modifying query.
	 */
	public function affectedRows(): int;

	/**
	 * Returns the ID generated by the last INSERT operation.
	 *
	 * Note:
	 * - Backends may return int (auto-increment) or string (UUID).
	 */
	public function insertId(): int|string;

	/**
	 * Escapes a string for safe inclusion in SQL queries.
	 *
	 * Semantics:
	 * - This method MUST return a quoted-safe string fragment.
	 * - Consumers MUST still handle surrounding quotes themselves.
	 */
	public function escape(string $str): string;

	/**
	 * Indicates whether the last executed query resulted in an error.
	 */
	public function isError(): bool;

	/**
	 * Returns the numeric error code of the last error.
	 *
	 * Note (matches current MysqlDatabase behavior):
	 * - Returns 0 if no error occurred.
	 */
	public function errorNumber(): int;

	/**
	 * Returns the error message of the last error.
	 *
	 * Note (matches current MysqlDatabase behavior):
	 * - Returns an empty string if no error occurred.
	 */
	public function errorMessage(): string;
}
